### PR TITLE
fix lifecycle method in BaseTable component

### PR DESCRIPTION
**Pull request by ShahAnuj2610**
#10 done

### CODE REVIEW

**Comment by ShahAnuj2610** [comment]
> Thank you for your contribution, I planned to use `gDSFP` to replace the current `cWRP`, not sure if this change would effect the performance

ok.

**Comment by nihgwu** [comment]
@ShahAnuj2610 Let's hold for a while for me to test the impact, thanks

**Comment by nihgwu** [comment]
Sorry I can't land this PR right now, as we use this component everywhere internally, so I have to make sure if this change would impact our current usage, I'll try to find some time to work on this PR.

**Comment by nihgwu** [comment]
Hi @ShahAnuj2610 Thanks for your contribution again, as I explained before, it's not a simple replacement from `cWRP` to `cDU`, we need do more for optimization, finally I got some time working on it, see #85 , so I'm going to close this one, I'm so sorry

**Pull request closed without merging**
