### PR TITLE
Add type definitions

### PR DESCRIPTION
**Pull request by sskiswani**
adds type definitions for v1.7.3. did some basic testing to make sure they were working well in my environment. I can update the eslint config to lint these files if you'd like.

For reference, the [single file version](https://gist.github.com/sskiswani/c16d3b70186ec3dc46b5d84446f393f3) doesn't seem to work when bundled with a module so I had to split them out.

### CODE REVIEW

**Comment by nihgwu** [comment]
@sskiswani YOU ARE AWESOME, I'll check it out tomorrow

As I said in the email, I'm working on #85, after that, we will work on the V2 on master branch, thank you for your contribution

**Comment by sskiswani** [comment]
Sorry for the delay... as far as I can tell, the only way to get the relative imports working is to move the type definition files to the root of the folder when publishing to npm. 

I haven't been able to get it to work any other way.

**Comment by nihgwu** [comment]
@sskiswani I'm the one to say sorry, I'm on my vacation and don't have enough time on the ts port, I'll pick it up as soon as I can, thanks

**Comment by nihgwu** [comment]
@sskiswani hey, thanks for your continuing work on this PR, now I'm thinking to postpone the idea to add typings for V1 as it requires more improvements in the future, but I don't think we have enough energy to maintain the typings for V1, so I think we can focus on the work on writing using TS for V2, WDYT? I think you can publish the typings to another package if necessary

**Comment by nihgwu** [comment]
OK, let's move forward and close this one, thanks

**Comment by mike-lischke** [comment]
@sskiswani Have you actually submitted the typings? I still cannot get any via `npm install`.

**Pull request closed without merging**
